USE [master]
GO

/****** Object:  Database [iebc3]    Script Date: 09/19/2017 20:14:21 ******/
CREATE DATABASE [iebc3] ON  PRIMARY 
( NAME = N'iebc3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\iebc3.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'iebc3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\iebc3_log.LDF' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [iebc3] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iebc3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iebc3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iebc3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iebc3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iebc3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iebc3] SET ARITHABORT OFF 
GO

ALTER DATABASE [iebc3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iebc3] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [iebc3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iebc3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iebc3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iebc3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iebc3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iebc3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iebc3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iebc3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iebc3] SET  ENABLE_BROKER 
GO

ALTER DATABASE [iebc3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iebc3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iebc3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iebc3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iebc3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iebc3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iebc3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iebc3] SET  READ_WRITE 
GO

ALTER DATABASE [iebc3] SET RECOVERY FULL 
GO

ALTER DATABASE [iebc3] SET  MULTI_USER 
GO

ALTER DATABASE [iebc3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iebc3] SET DB_CHAINING OFF 
GO


